INSERT INTO AIRCRAFT_SPECIFICATIONS (AIRCRAFT_SPECIFICATION_ID, STRUCTURE, FUEL_CAPACITY, MIN_SPEED, MAX_SPEED, MAX_ALTITUDE, SPECIFICATION_CODE) VALUES (1, 3, 10, 2, 6, 5, 'Tunderbolt');
INSERT INTO AIRCRAFT_SPECIFICATIONS (AIRCRAFT_SPECIFICATION_ID, STRUCTURE, FUEL_CAPACITY, MIN_SPEED, MAX_SPEED, MAX_ALTITUDE, SPECIFICATION_CODE) VALUES (2, 2, 8, 3, 8, 4, 'Vulture');
INSERT INTO AIRCRAFTS (AIRCRAFT_ID, ALTITUDE, FUEL, NAME, SPECIFICATION_ID, SPEED) VALUES (1, 5, 6,
                                                                                           'Executioner', 1, 4);
INSERT INTO AIRCRAFTS (AIRCRAFT_ID, ALTITUDE, FUEL, NAME, SPECIFICATION_ID, SPEED) VALUES (2, 3, 3,
                                                                                           'Dakkajet', 2, 3);
INSERT INTO MERCENARIES (MERCENARY_ID, BODY_SKILL, COMBAT_SKILL, FIRST_NAME, LAST_NAME) VALUES
    (1, 4, 4, 'Han', 'Solo');
INSERT INTO MERCENARIES (MERCENARY_ID, BODY_SKILL, COMBAT_SKILL, FIRST_NAME, LAST_NAME) VALUES
    (2, 8, 8, 'Luke', 'Skywalker');
INSERT INTO COMPARTMENTS (COMPARTMENT_ID, AIRCRAFT_ID, NAME) VALUES (1, 1, 'pilot cockpit');
INSERT INTO COMPARTMENTS (COMPARTMENT_ID, AIRCRAFT_ID, NAME) VALUES (2, 1, 'storage compartment');INSERT INTO COMPARTMENTS (COMPARTMENT_ID, AIRCRAFT_ID, NAME) VALUES (3, 1, 'machine room');
INSERT INTO COMPARTMENTS (COMPARTMENT_ID, AIRCRAFT_ID, NAME) VALUES (4, 1, 'weapon compartmentrear');